### ISSUE TITLE
Create dedicated repository for redhat_satellite6_storage and publish it to Ansible Galaxy

### ISSUE THREAD

**Issue by stdevel** [rhtconsulting/ansible-redhat_satellite6#10]
I find the ``redhat_satellite6_storage`` pretty useful. Unfortunately it is not published on Ansible Galaxy so I need to manually copy it.

Are there plans to change this?

Best wishes,
Christian.

**Comment by itewk** [comment]
@stdevel first off. Awesome. Glad to hear someone finds something in here useful.

 yes. Ideally that role would move to https://github.com/oasis-roles and then anything in there is pushed to ansible galaxy. but it is not high on anyone's list of things to do right now. I actually didn't think anyone was using any of this.

You could always extract the role from here and put it in your own local git and pull down as a source role that way.

**Comment by stdevel** [comment]
Thanks for the feedback!
Is there anything I can do to make it being part of oasis-roles? I could improve the role a little bit, clean-up the code and add molecule tests to it. Maybe you guys could publish it, then? :)

**Comment by itewk** [comment]
@stdevel I just reached out to the folks who maintain the OASIS repos to see process for moving the role there. I'll update here in a couple days.

In the mean time, any PRs you want to make to it feel free to do them here and I will review. ALso, I know OASIS really likes to have tests on their roles, which trhis role doesnt have any yet, so if you happen to know how to write molecule and watn to contribute that here, it would make moving it and publishing it to galaxy that much eaiser.

**Comment by stdevel** [comment]
Thanks for the feedback, @itewk - just created Pull Request #12 as discussed.

**Comment by itewk** [comment]
This is going to be tracked from https://github.com/oasis-roles/ansible-role-redhat_satellite6_storage/issues/2 from here on out. one step closer.
