### ISSUE TITLE
satellite_register - update to use bootstrap.py

### ISSUE THREAD

**Issue by itewk** [rhtconsulting/ansible-redhat_satellite6#4]
the satellite registration should really be done with the boostrap.py script

**Comment by johannes-cabal** [comment]
Closing as this was resolved in #5

**Comment by johannes-cabal** [comment]
Ah, nevermind. @itewk can you close this issue or do you think we still need some more content?

**Comment by itewk** [comment]
@josh-springer i would say this is done. Unless you think something is missing?
